name: Publish images

on:
  release:
    types:
      - published

env:
  RELEASE_VERSION: ${{ github.event.release.tag_name }}
  RELEASE_CREATED_AT: ${{ github.event.release.published_at }}

jobs:
  github-container-registry:
    name: Github Container Registry
    runs-on: ubuntu-20.04
    environment:
      name: Marketplace
      url: https://github.com/marketplace/actions/mantainer?version=$RELEASE_VERSION
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: GHCR Authentication
        run: |
          echo ${{ env.ACCESS_TOKEN }}
            | docker login ghcr.io -u ${{ env.ACCESS_USER }} --password-stdin

      - name: Building
        run: |
          docker build ./ --file ./Dockerfile \
                          --tag ghcr.io/covalentteam/mantainer:$RELEASE_VERSION \
                          --build-arg RELEASE_VERSION \
                          --build-arg RELEASE_CREATED_AT

      - name: Publishing release version
        run: docker push ghcr.io/covalentteam/mantaine:$RELEASE_VERSION